config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'pages/bedrijven'
  get 'pages/investeerders'
  get 'pages/over_CFOhulp'

  resources :demo_clients, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/demo_client.rb
class DemoClient < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/demo_clients_controller.rb
class DemoClientsController < ApplicationController
  skip_before_action :authenticate_user!, :raise => false
  # skip_after_action :verify_authorized

def new
  @demo_client = DemoClient.new
end

def create
  @demo_client = DemoClient.new(demo_client_params)
  if @demo_client.save
      flash[:notice] = "Bedankt, we nemen snel contact met je op!"
      mail = UserMailer.with(demo_client: @demo_client).lead
      mail.deliver_now
      redirect_to root_path

    else
      flash[:error] = "Helaas moet het gehele formulier ingevuld zijn"
      redirect_to root_path
    end
end

private
def demo_client_params
    params.require(:demo_client).permit(:company, :first_name, :last_name, :email, :telephone, :message, :method)
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :bedrijven, :investeerders, :over_CFOhulp]

  def home
  end

  def bedrijven
  end

   def investeerders
  end

  def over_CFOhulp
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/demo_clients/new.html.erb
<div class="over_ons_container">
  <div class="lead-form-container">
    <!-- <div class="avatar_over_ons_container"> -->



<%= simple_form_for(DemoClient.new) do |f| %>
<div class="row">
  <div class="col-12 col-lg-12"><%= f.input :company, placeholder: 'Bedrijfsnaam', label:false %></div>
</div>
<div class="row">
  <div class="col-12 col-lg-12"><%= f.input :first_name, placeholder: 'Voornaam', label:false %></div>
  <div class="col col-12 col-lg-12"><%= f.input :last_name, placeholder: 'Achternaam', label:false %></div>
</div>

<div class="row">
  <div class="col col-12 col-lg-12" ><%= f.input :email, placeholder: 'Email', label:false %></div>
  <div class="col col-12 col-lg-12" ><%= f.input :telephone, placeholder: 'Telefoonnummer', label:false %></div>
</div>

<div class="row">
  <div class="col-12">
    <%= f.input :message, placeholder: 'Bericht', label:false, :input_html => {:style => 'width: 100%', :rows => 12} %>
  </div>
</div>

<div class="signup-btn"><%= f.button :submit, "Verzenden" %></div>
<% end %>


<!-- </div> -->
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CFOhulp - CFO services</title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans:wght@400;700&display=swap" rel="stylesheet">
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/bedrijven.html.erb
<!-- <div class="landing-page-middle bedrijven-banner">
  <div class="landing-page-middle-left">
    <h1>"Wij helpen ondernemers door het standaardiseren van financiële processen en het inzichtelijk maken van de performance"</h1>
    <p><i> - Rob (Eigenaar CFOhulp) </i></p>
  </div>
</div> -->
<div class="banner-bedrijven">
<div class="landing-page-middle">
    <h1>"Wij helpen ondernemers met het standaardiseren van financiële processen en het inzichtelijk maken van de performance"</h1>
        <p><i> - Rob (Eigenaar CFOhulp) </i></p>
        <div> <%= link_to "Maak een afspraak", new_demo_client_path, class: "btn btn-flat" %></div>
  </div>
</div>

<div class="landing-page-services-container">

  <div class="landing-page-services-bedrijven">
    <div class="landing-page-services-bedrijven-item">
      <i class="fas fa-file-invoice fa-4x"></i>
      <h5>Financiële reporting</h5>
      <p>Krijg een duidelijk beeld van de activiteiten van uw bedrijf met interne en externe financiële rapportage.</p>
    </div>
    <div class="landing-page-services-bedrijven-item">
      <i class="fas fa-euro-sign fa-4x"></i>
      <h5>Cash flow management</h5>
      <p>Stroomlijn debiteur-en crediteurbeheer om de inkomsten, uitgaven en het gebruik van geld in uw bedrijf effectief te volgen.</p>
    </div>
    <div class="landing-page-services-bedrijven-item">
      <i class="fas fa-chart-line fa-4x"></i>
      <h5>Performance tracking</h5>
      <p>Verkrijg belangrijke inzichten in prestaties met robuuste gegevensverzameling en dynamische KPI-trackingdashboards.</p>
    </div>
    <div class="landing-page-services-bedrijven-item">
      <i class="fas fa-handshake fa-4x"></i>
      <h5>Financiering en overnames</h5>
      <p>Geef uw bedrijf de kans om strategische kansen te benutten door middel van (bank)leningen, investeringen in aandelen, fusies en overnames.</p>
    </div>
    <div class="landing-page-services-bedrijven-item">
      <i class="fas fa-cogs fa-4x"></i>
      <h5>Budget kosten beheersing</h5>
      <p>Identificeer kostenbesparingen en implementeer efficiënte maandelijkse budgetteringsprocessen om de cashflow te optimaliseren.</p>
    </div>
    <div class="landing-page-services-bedrijven-item">
      <i class="fas fa-chart-bar fa-4x"></i>
      <h5>Staat uw behoefte er niet bij?</h5>
      <p>Schrijf ons een email en dan proberen we samen te kijken naar de mogelijkheden.</p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner">
<div class="landing-page-middle">
    <h1><b>Ga jij maar ondernemen, CFOhulp doet de rest...</b></h1>
    <p><i> - CFOhulp </i></p>
    <div> <%= link_to "Maak een afspraak", new_demo_client_path, class: "btn btn-flat" %></div>
  </div>
</div>


<div class="landing-page-services-container">
  <div class="landing-page-services">
    <div class="landing-page-services-item">
      <%= link_to pages_bedrijven_path do %>
      <!-- <div class="landing-page-services-item"> -->
        <h4>Inrichting financiële infrastructuur en reporting</h4>
        <p>Krijg hulp bij het maken van een financiële professionaliseringsslag!</p>
        <%= link_to "Lees meer...", pages_bedrijven_path, class: "lees-meer" %>
      <!-- </div> -->
    <% end %>
  </div>
  <!-- </div> -->

    <!-- <div class="landing-page-services-item"><h4>Ondersteuning bij aan- en/of verkooptraject</h4></div> -->
     <!-- <div class="landing-page-services-item"><h4>Banklening ophalen</h4></div> -->
     <div class="landing-page-services-item">
         <%= link_to pages_investeerders_path do %>
        <h4>Voor Investeerders*</h4>
        <p>Ondersteuning bij portfolio management, het invoeren van reporting standaarden en nog veel meer </p>
        <%= link_to "Lees meer...", pages_investeerders_path, class: "lees-meer" %>
        <% end %>
    </div>
    <div class="landing-page-services-item">
      <%= link_to pages_bedrijven_path do %>
      <h4> CFO-as-a-Service</h4>
      <p>Geen full-time CFO nodig, maar wel maandelijkse ondersteuning voor financiële zaken? Probeer CFO-as-a-Service! </p>
      <%= link_to "Lees meer...", pages_bedrijven_path, class: "lees-meer" %>
      <% end %>
    </div>
    <div class="landing-page-services-item">
      <%= link_to pages_bedrijven_path do %>
      <h4>Op maat</h4>
      <p>Staat uw financiële vraag er niet bij? Laten we dan samen eens kijken naar een op maat gemaakte oplossing!</p>
      <%= link_to "Lees meer...", pages_bedrijven_path, class: "lees-meer" %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/investeerders.html.erb
<!-- <div class="landing-page-middle bedrijven-banner">
  <div class="landing-page-middle-left">
    <h1>"Wij ondersteunen investeerders bij portfolio management en tijdens exit-en investeringsprocessen"</h1>
    <p><i> - Rob (Eigenaar CFOhulp) </i></p>
  </div>
</div> -->
<div class="banner-investeerder">
  <div class="landing-page-middle">
    <h1>"Wij ondersteunen investeerders en haar portfolio bedrijven bij het profesionaliseren van de financiële processen"</h1>
    <p><i> - Rob (Eigenaar CFOhulp) </i></p>
    <div> <%= link_to "Maak een afspraak", new_demo_client_path, class: "btn btn-flat" %></div>
  </div>
</div>

<div class="landing-page-services-container">
  <div class="landing-page-services-bedrijven">
    <div class="landing-page-services-investeerders-item">
      <div class="avatar-investeerder-container">
        <div class="avatar-investeerder">
          <i class="fas fa-file-invoice fa-4x"></i>
        </div>
      </div>
      <h5>Portfolio management</h5>
      <i>Heeft een individueel portfolio bedrijf extra ondersteuning nodig bij het inrichten van financiële processen? Of wilt u portfoliobreed een profesionaliseringsslag doorvoeren door middel van een nieuwe reportingstandaard? <b>Wij helpen!</b></i>

      <ul>
        <li>Financiële reporting</li>
        <li>Cash flow management</li>
        <li>Performance tracking</li>
        <li>Budget kosten beheersing</li>
      </ul>

      <h6><b>Staat uw vraag er niet bij, neem dan contact op en dan kijken wij samen naar de mogelijkheden!</b></h6>
    </div>
    <div class="landing-page-services-investeerders-item">
      <div class="avatar-investeerder-container">
        <div class="avatar-investeerder">
          <i class="fas fa-user fa-4x"></i>
        </div>
      </div>
      <h5>CFO-as-a-Service</h5>
      <i>Hebben portfolio bedrijven periodiek ondersteuning nodig, maar geen full-time CFO of controller? Maak gebruik van CFO-as-a-Service (maandelijks opzegbaar).</i>

      <div> <%= link_to "Bekijk voorbeeld werkzaamheden", pages_bedrijven_path, class: "btn btn-flat btn-saas" %></div>
    </div>
    <div class="landing-page-services-investeerders-item">
      <div class="avatar-investeerder-container">
        <div class="avatar-investeerder">
          <i class="fas fa-handshake fa-4x"></i>
        </div>
      </div>
      <h5>Begeleiding Investeringsprocessen</h5>
      <i>CFOhulp kan portfolio bedrijven begeleiden en ondersteunen bij het ophalen van financiering.</i>

      <ul>
        <li>M&A processen</li>
        <li>Groeifinanciering</li>
        <li>Banklening</li>
        <li>Alternatieve financieringsvormen</li>
      </ul>

      <h6><b>Buiten de begeleiding van een geheel proces, helpen wij ook bij individuele onderdelen. Voorbeelden zijn het opstellen van een IM of het inrichten van een dataroom.</b></h6>
    </div>
  </div>
</div>

app/views/pages/over_CFOhulp.html.erb
<div class="over_ons_container">
  <div class="over_ons_tekst">
    <div class="avatar_over_ons_container">
      <div class="avatar_over_ons">
      </div>
    </div>
    <div class="btn-container">
      <div> <%= link_to "Kennismaken?", new_demo_client_path, class: "btn btn-flat" %></div>
    </div>
    <div class="over_ons_tekst_container">
      <h1>Hallo,</h1><br>

      <p>Mijn naam is Rob, een voormalig investeerder bij één van Europa's grotere investeerders in software bedrijven.</p>

      <p>Ik heb de unieke mogelijkheid gehad om jarenlang met CEO's en CFO's samen te werken op thema's zoals:</p>
      <ul>
        <li>
          <b>Professionaliserings vraagstukken.</b>
          <br>
          Hoe kan de (financiële) organisatie worden ingericht, zodat de onderneming beter kan worden gemonitord en op basis van data worden aangestuurd?
        </li>
        <br>
        <li>
          <b>Financieringsvraagstukken.</b>
          <br>
          Wat zijn de financieringsopties om ons business model te financieren?
        </li>
        <br>
        <li>
          <b>Aan en/of verkoopvraagstukken.</b>
          <br>
          Hoe werkt het proces rondom een strategische acquisitie en/of verkoop van een bedrijf. Wat heb ik nodig en hoe geef ik het proces invulling?
        </li>
      </ul>

      <p>Met CFOhulp probeer ik nu ook andere bedrijven te helpen met het neerzetten en/of bijhouden van de financiële organisatie.</p>

      <p>Hierdoor krijgt u inzicht in de financiële performance van uw bedrijf en kunt u deze gebruiken als ondersteuning om de juiste keuzes te maken voor uw bedrijfsvoering.</p>

      <p>Groeten,</p>

      <h3>Rob</h3>


    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <p>CFOhulp</p>
  <p>E: rob@cfohulp.nl</p>
  <p>T: 06 33 189 189</p>
  <p>KvK: 78220998 </p>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light navbar-landing-page">
  <%= link_to root_path do %>
    <div class="landing-page-logo">
      <p>CFOhulp</p>
    </div>
    <% end %>
    <div>
  <button id="navbar-menu-landing-page" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item navbar-home-item landing-page-navbar-right-item">
        <div class="nav-link">
          <!-- Bedrijven -->
          <%= link_to "Bedrijven", pages_bedrijven_path %>
        </div>
      </li>
      <li class="nav-item navbar-home-item landing-page-navbar-right-item">
        <div class="nav-link">
          <%= link_to "Investeerders", pages_investeerders_path %>
        </div>
      </li>
      <li class="nav-item navbar-home-item landing-page-navbar-right-item">
        <div class="nav-link">
          <%= link_to "Over CFOhulp", pages_over_CFOhulp_path %>
        </div>
      </li>

      <!-- test -->
    </ul>
  </div>
  </div>
</nav>

<script>
// $(document).ready(function(){
  // document.addEventListener("turbolinks:load", function(event) {
// $(document).on('turbolinks:load', function() {
  $( document ).ready(function() {
    $('.dropdown-submenu a.test').on("click", function(e){
      // console.log(this)
      $(this).next('ul').toggle();
      e.stopPropagation();
      e.preventDefault();
    });
    $('#dropdownMenuButton').on("click", function(e){
      $('.navbar-collapse').toggle();
      // $(this).next('ul').toggle();
      e.stopPropagation();
      e.preventDefault();
    });
  // });
  $('#navbar-menu-landing-page').on("click", function(e){
      $('.navbar-collapse').toggle();
      // $('.navbar-collapse').toggle();
    });
  });
// });



//   document.addEventListener("turbolinks:load", function(event) {
//   $('#dropdownMenuButton').on("click", function(e){
//     $(this).next('ul').toggle();
//     e.stopPropagation();
//     e.preventDefault();
//   });
// });

</script>